name: Profanity check

on: 
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Profanity check
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
